import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700', '800', '900']
});



export const metadata = {
  title: "Skill-Sphere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme='light'
      lang="en"
      className={`${poppins.className} h-full antialiased`}
    >
      <body
        className="bg-[#fafafa]">
        <main className="mx-auto max-w-480">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
