import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700', '800', '900']
});



export const metadata = {
  title: "Skill-Sphere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme='light'
      lang="en"
      className={`${poppins.className} h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
